home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^profile/$', views.edit_user, name='profile'),
    url(r'^log/$', views.log_page, name='log_page'),
]

lebaguette/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^status/', include('status.urls')),
    url(r'^requestmedia/', include('requestmedia.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)

home/models.py
from __future__ import unicode_literals

from django.db import models


class ServerMessage(models.Model):
    message = models.TextField('Message',
                               blank=False,
                               null=False)
    datetime_created = models.DateTimeField(auto_now_add=True)

home/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

from .models import ServerMessage


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = \
            "mdl-textfield__input"
        self.fields['first_name'].widget.attrs['class'] = \
            "mdl-textfield__input"
        self.fields['last_name'].widget.attrs['class'] = \
            "mdl-textfield__input"
        self.fields['email'].widget.attrs['class'] = \
            "mdl-textfield__input"


class ServerMessageForm(ModelForm):
    class Meta:
        model = ServerMessage
        fields = ['message']


class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = "mdl-textfield__input"
        self.fields['username'].widget.attrs['required'] = True
        self.fields['password'].widget.attrs['class'] = "mdl-textfield__input"
        self.fields['password'].widget.attrs['required'] = True


class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs['class'] = \
            "mdl-textfield__input"
        self.fields['new_password1'].widget.attrs['class'] = \
            "mdl-textfield__input"
        self.fields['new_password2'].widget.attrs['class'] = \
            "mdl-textfield__input"

home/views.py
import os

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings

from .forms import UserForm, ServerMessageForm
from .forms import CustomAuthenticationForm, CustomPasswordChangeForm
from .models import ServerMessage


def login_user(request):
    if request.user.is_authenticated:
        return redirect(settings.LOGIN_REDIRECT_URL)

    form = CustomAuthenticationForm(None, request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            user = form.get_user()
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(settings.LOGIN_REDIRECT_URL)
    return render(request, 'login.html', locals())


def logout_user(request):
    logout(request)
    return redirect('/login/')


@login_required
def edit_user(request):
    user = request.user
    user_change_form = UserForm(request.POST or None, instance=request.user)
    password_change_form = CustomPasswordChangeForm(
        user=request.user,
        data=request.POST or None)
    if not(password_change_form.has_changed()):
        password_change_form.errors.clear()
    if request.method == 'POST':
        if user_change_form.is_valid():
            user_change_form.save()
        if password_change_form.has_changed() and \
                password_change_form.is_valid():
            password_change_form.save()
    return render(request, 'profile.html', locals())


@login_required
def home_page(request):
    try:
        latest_message = ServerMessage.objects.\
            latest('datetime_created').message
    except ObjectDoesNotExist:
        latest_message = "No message has been added yet!"
    if request.user.is_staff:
        message_form = ServerMessageForm(request.POST or None)
        message_form.fields['message'].widget.attrs['class'] = \
            "mdl-textfield__input"
        message_form.fields['message'].widget.attrs['type'] = \
            "text"
        message_form.fields['message'].widget.attrs['rows'] = \
            "5"
        if request.method == 'POST':
            if message_form.is_valid():
                message_form.save()
                return redirect('/')
    return render(request, 'home.html', locals())


@login_required
def log_page(request):
    log_path = os.path.join(settings.BASE_DIR, 'log/')
    log_files = os.listdir(log_path)
    selected_log = (request.GET.get('log') or log_files[0])
    if request.method == 'POST':
        file_to_clear = request.POST.get('file_name')
        open(log_path + file_to_clear, 'w').close()
        return redirect('.?log={}'.format(selected_log))
    log_file = open(log_path + '{}'.format(selected_log), 'r').read().split('message_end')
    log_result = []
    for log_file_row in log_file:
        if log_file_row != '' and log_file_row != '\n':
            log_result.append(log_file_row.split('|'))
    return render(request, 'log_page.html', locals())

home/templates/home.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block title %}Lebaguette - Home{% endblock %}
{% block body %}
  <div class="layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
    <header class="header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
      <div class="mdl-layout__header-row">
        <span class="mdl-layout-title">There's no place like home</span>
        <div class="mdl-layout-spacer"></div>
        <label id="logout" class="mdl-button mdl-js-button mdl-button--icon" for="search">
          <a href="/logout"><i class="material-icons">power_settings_new</i></a>
        </label>
        <div class="mdl-tooltip" for="logout">
          Bye bye
        </div>
      </div>
    </header>
    {% include "base/drawer.html" %}
    <main class="mdl-layout__content mdl-color--grey-100">
      <div class="mdl-grid container">
        <div class="cards mdl-cell mdl-cell--12-col mdl-grid">
          <div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--12-col">
            <div class="mdl-card__title mdl-color--green-400">
              <h2 class="mdl-card__title-text">Server message</h2>
            </div>
            <div class="mdl-card__supporting-text">
              <span class="mdl-typography--title">{{ latest_message }}</span>
            </div>
          </div>
          {% if request.user.is_staff %}
          <div class="mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
            <form id="id_message" method="post" action="{% url 'home' %}" class="mdl-cell mdl-cell--12-col mdl-grid">
              {% csrf_token %}
              <div class="mdl-textfield mdl-js-textfield mdl-cell mdl-cell--12-col">
                {{ message_form.message }}
                <label class="mdl-textfield__label" for="id_message">Enter new message of the day...</label>
              </div>
              <div class="mdl-card__actions">
                <a onclick="$('#id_message').submit();" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" data-upgraded=",MaterialButton,MaterialRipple">
                  Update motd
                <span class="mdl-button__ripple-container"><span class="mdl-ripple is-animating" style="width: 272.026px; height: 272.026px; transform: translate(-50%, -50%) translate(78px, 16px);"></span></span></a>
              </div>
            </form>
          </div>
          {% endif %}
        </div>
      </div>
    </main>
  </div>
  {% endblock %}

home/templates/log_page.html
{% extends "base/base.html" %} {% load staticfiles %} {% block title %}Lebaguette - Home{% endblock %} {% block body %}
<div class="layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
  <header class="header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Log Messages</span>
      <div class="mdl-layout-spacer"></div>
      <form name="clear_log_form" action="#" method="post">
        {% csrf_token %}
        <input type="hidden" name="file_name" value="{{ selected_log }}">
        <label id="clear_log" class="mdl-button mdl-js-button mdl-button--icon" for="search">
            <a href="#" onclick="$(this).closest('form').submit()"><i class="material-icons">delete</i></a>
        </label>
        <div class="mdl-tooltip" for="logout">
            Clear Log File
        </div>
      </form>
      <label id="logout" class="mdl-button mdl-js-button mdl-button--icon" for="search">
        <a href="/logout"><i class="material-icons">power_settings_new</i></a>
      </label>
      <div class="mdl-tooltip" for="logout">
        Bye bye
      </div>
    </div>
  </header>
  {% include "base/drawer.html" %}
  <main class="mdl-layout__content mdl-color--grey-100">
    <div class="mdl-grid mdl-shadow--1dp">
      <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect mdl-cell mdl-cell--12-col mdl-color--white">
        <div class="mdl-tabs__tab-bar">
          {% for log_file in log_files %}
            <a href=".?log={{ log_file }}" class="mdl-layout__tab {% if log_file == selected_log %}is-active{% endif %}">{{ log_file }}</a>
          {% endfor %}
        </div>
        <div class="mdl-grid">
          <div class="mdl-layout-spacer"></div>
          {% if log_result %}
            <table class="mdl-data-table mdl-js-data-table mdl-data-table">
              <thead>
                <tr>
                  <th class="mdl-data-table__cell--non-numeric">Type</th>
                  <th class="mdl-data-table__cell--non-numeric">Date Time</th>
                  <th class="mdl-data-table__cell--non-numeric">Path</th>
                  <th class="mdl-data-table__cell--non-numeric">Message</th>
                </tr>
              </thead>
              <tbody>
                {% for log_row in log_result %}
                  <tr>
                    {% for log_item in log_row %}
                    <td {% if 'Traceback' in log_item %}colspan="4" {% endif %}class="td-wrap mdl-data-table__cell--non-numeric">{{ log_item }}</td>
                    {% endfor %}
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
            <div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--3-col">
              <div class="mdl-card__title mdl-card--border">
                <i class="material-icons" role="presentation">check_circle</i>
                <h1 class="mdl-card__title-text">Good job!</h2>
              </div>
              <div class="mdl-card__supporting-text">
                <h4>There are no records in this log!</h4>
              </div>
            </div>
          {% endif %}
          <div class="mdl-layout-spacer"></div>
        </div>
      </div>
    </div>
  </main>
</div>
{% endblock %}

home/templates/login.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block title %}Lebaguette - Login{% endblock %}
{% block body %}
  <div class="mdl-layout mdl-layout-login mdl-js-layout mdl-color--grey-100">
    <main class="mdl-layout__content mdl-layout__content-login">
      <div class="mdl-card mdl-shadow--6dp">
        <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
          <h2 class="mdl-card__title-text">Le Baguette</h2>
        </div>
        <div class="mdl-card__supporting-text">
          <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="mdl-textfield mdl-js-textfield">
              {{ form.username }}
              <label class="mdl-textfield__label" for="id_username">Username</label>
              {% if form.errors.username %}
              <div id="id_username_error" class="error-tooltip">
                {% for error in form.errors.username %}
                  {{ error|escape }}<br>
                {% endfor %}
              </div>
              {% endif %}
            </div>
            <div class="mdl-textfield mdl-js-textfield">
              {{ form.password }}
              <label class="mdl-textfield__label" for="id_password">Password</label>
              {% if form.errors.password %}
              <div id="id_username_error" class="error-tooltip">
                {% for error in form.errors.password %}
                  {{ error|escape }}<br>
                {% endfor %}
              </div>
              {% endif %}
            </div>
            <div class="mdl-card__actions">
              <button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" type="submit">Log in</button>
            </div>
          </form>
        {% if form.non_field_errors %}
        <div id="non_field_errors" class="error-tooltip-non">
          {% for error in form.non_field_errors %}
            {{ error|escape }}<br>
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </main>
  </div>
{% endblock %}

home/templates/profile.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block title %}Lebaguette - Profile{% endblock %}
{% block body %}
  <div class="layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
    <header class="header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
      <div class="mdl-layout__header-row">
        <span class="mdl-layout-title">Account setup</span>
        <div class="mdl-layout-spacer"></div>
        <label id="logout" class="mdl-button mdl-js-button mdl-button--icon" for="search">
          <a href="/logout"><i class="material-icons">power_settings_new</i></a>
        </label>
        <div class="mdl-tooltip" for="logout">
          Bye bye
        </div>
      </div>
    </header>
    {% include "base/drawer.html" %}
    <main class="mdl-layout__content mdl-color--grey-100">
      <div class="mdl-grid container">
        <div class="cards mdl-cell mdl-cell--12-col mdl-grid">
          <div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--12-col-tablet mdl-cell--3-col">
            <div class="mdl-card__title mdl-card--expand card-profile">
              <div class="mdl-layout-spacer"></div>
              <img src="{% static "images/ninja.png" %}" alt="profile image" class="card-profile--avatar mdl-shadow--2dp">
              <div class="mdl-layout-spacer"></div>
            </div>
            <div class="mdl-card__supporting-text card-profile--stats mdl-grid">
              <div class="mdl-cell mdl-cell--12-col separator"></div>
              <div class="mdl-cell mdl-cell--12-col mdl-typography--text-center">
                <span class="mdl-typography--title">{{ request.user.first_name }} {{ request.user.last_name }}</span>
              </div>
            </div>
            <div class="mdl-card__actions mdl-card--border">
              <a id="submit_form" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" data-upgraded=",MaterialButton,MaterialRipple">
                Save profile
              <span class="mdl-button__ripple-container"><span class="mdl-ripple is-animating" style="width: 272.026px; height: 272.026px; transform: translate(-50%, -50%) translate(78px, 16px);"></span></span></a>
            </div>
          </div>
          <div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--12-col-tablet mdl-cell--9-col" style="overflow:visible;">
            <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
              <div class="mdl-tabs__tab-bar">
                <a href="#profile-panel" class="mdl-tabs__tab is-active">Personal information</a>
                <a href="#password-panel" class="mdl-tabs__tab">Password</a>
              </div>
              <form id="profile_form" class="input-profile" method="post" action="{% url 'profile' %}">
                <div class="mdl-tabs__panel is-active mdl-grid mdl-cell mdl-cell--12-col" id="profile-panel">
                  {% csrf_token %}
                  <div class="input-profile">
                    <div class="mdl-textfield mdl-js-textfield">
                      {{ user_change_form.username }}
                      <label class="mdl-textfield__label" for="id_username">Login name...</label>
                      {% if user_change_form.errors.username %}
                      <div id="id_username_error" class="error-tooltip">
                        {% for error in user_change_form.errors.username %}
                          {{ error|escape }}<br>
                        {% endfor %}
                      </div>
                      {% endif %}
                    </div>
                  </div>
                  <div class="input-profile">
                    <div class="mdl-textfield mdl-js-textfield">
                      {{ user_change_form.first_name }}
                      <label class="mdl-textfield__label" for="id_first_name">First name...</label>
                      {% if user_change_form.errors.first_name %}
                      <div id="id_first_name_error" class="error-tooltip">
                        {% for error in user_change_form.errors.first_name %}
                          {{ error|escape }}<br>
                        {% endfor %}
                      </div>
                      {% endif %}
                    </div>
                  </div>
                  <div class="input-profile">
                    <div class="mdl-textfield mdl-js-textfield">
                      {{ user_change_form.last_name }}
                      <label class="mdl-textfield__label" for="id_last_name">Last name...</label>
                      {% if user_change_form.errors.last_name %}
                      <div id="id_last_name_error" class="error-tooltip">
                        {% for error in user_change_form.errors.last_name %}
                          {{ error|escape }}<br>
                        {% endfor %}
                      </div>
                      {% endif %}
                    </div>
                  </div>
                  <div class="input-profile">
                    <div class="mdl-textfield mdl-js-textfield">
                      {{ user_change_form.email }}
                      <label class="mdl-textfield__label" for="id_email">e-mail...</label>
                      {% if user_change_form.errors.email %}
                      <div id="id_email" class="error-tooltip">
                        {% for error in user_change_form.errors.email %}
                          {{ error|escape }}<br>
                        {% endfor %}
                      </div>
                      {% endif %}
                    </div>
                  </div>
                </div>
                <div class="mdl-tabs__panel mdl-grid" id="password-panel">
                  <div class="input-profile">
                      {{ password_change_form.non_field_errors.as_text }}
                    <div class="mdl-textfield mdl-js-textfield">
                      {{ password_change_form.old_password }}
                      <label class="mdl-textfield__label" for="id_old_password">Old password...</label>
                      {% if password_change_form.errors.old_password %}
                      <div id="id_old_password_error" class="error-tooltip">
                        {% for error in password_change_form.errors.old_password %}
                          {{ error|escape }}<br>
                        {% endfor %}
                      </div>
                      {% endif %}
                    </div>
                  </div>
                  <div class="input-profile">
                    <div class="mdl-textfield mdl-js-textfield">
                      {{ password_change_form.new_password1 }}
                      <label class="mdl-textfield__label" for="id_new_password1">New password...</label>
                      <div id="password_strength" class="mdl-progress mdl-js-progress"></div>
                      {% if password_change_form.errors.new_password1 %}
                      <div id="id_new_password1_error" class="error-tooltip">
                        {% for error in password_change_form.errors.new_password1 %}
                          {{ error|escape }}<br>
                        {% endfor %}
                      </div>
                      {% endif %}
                    </div>
                    <div id="password_tooltip" class="mdl-tooltip" for="id_new_password1">At least 8 characters</div>
                  </div>
                  <div class="mdl-layout-spacer"></div>
                  <div class="input-profile">
                    <div class="mdl-textfield mdl-js-textfield">
                      {{ password_change_form.new_password2 }}
                      <label class="mdl-textfield__label" for="id_new_password2">Repeat password...</label>
                      {% if password_change_form.errors.new_password2 %}
                      <div id="id_new_password2_error" class="error-tooltip">
                        {% for error in password_change_form.errors.new_password2 %}
                          {{ error|escape }}<br>
                        {% endfor %}
                      </div>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </form>
            </div>
            {% if user_change_form.non_field_errors %}
            <div id="non_field_errors" class="error-tooltip-non">
              {% for error in user_change_form.non_field_errors %}
                {{ error|escape }}<br>
              {% endfor %}
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </main>
  </div>
  {% endblock %}
  {% block post_load %}
    <script type = "text/javascript" src="{% static "js/profile.js" %}"></script>
  {% endblock %}